### ISSUE TITLE
Could not get unknown property 'FIREBASE_VERSION' for object of type

### ISSUE THREAD

**Issue by michaeljcoyne** [chemerisuk/cordova-plugin-firebase-analytics#55]
```
* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not get unknown property 'FIREBASE_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

`cli packages: (/Users/michael/Documents/sites/laravel/hybrid/node_modules)

    @ionic/cli-utils  : 1.7.0
    ionic (Ionic CLI) : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.0.1

`

**Comment by okonon** [comment]
@michaeljcoyne any luck resolving this issue?

**Comment by okonon** [comment]
I am having same issue here and any help will be appreciated.

**Comment by rafraph** [comment]
I have the same problem. Anyone found a solution please?

**Comment by Vivien-** [comment]
Samee issue here as well

**Comment by cherryholme7** [comment]
Same issue here. Do we know if this will be resolved?

**Comment by prantikv** [comment]
How does one specify the `FIREBASE_VERSION` variable?

**Comment by rafraph** [comment]
After lot of time I fixed it. The solution was by remove and reinstall the plugins or even all the packages. In addition I updated some versions.
It is hard to say what exactly solve the problem

**Comment by alexandre-pereira** [comment]
https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/55

Seems to have the same conflict, probably related to using both cordova-plugin-fcm and this one.

Anyone has a temporary fix?

**Comment by pwespi** [comment]
I have added the plugin to my ionic project with `ionic cordova plugin add cordova-plugin-firebase-analytics` and it works. In config.xml I have:
```
<plugin name="cordova-plugin-firebase-analytics" spec="^0.12.1">
    <variable name="FIREBASE_VERSION" value="11.0.+" />
</plugin>
```
Maybe this helps...

**Comment by royken** [comment]
Same error here. @pwespi I have done exactly the same and I have that in my config.xml file.
Any solution ?

**Comment by Lukizzle** [comment]
I'm also still facing this error. Removing and adding the firebase plugins or android platform didn't work. Neither did adding "classpath 'com.google.gms:google-services:3.0.0'" to the top level build.gradle dependencies. Any other suggestions?

**Comment by Darkarmour** [comment]
Hey Everyone! Previous version (0.12.0) solves the issue. Requires the google-services.json file to be placed inside the platforms->android of your project. Do check it

**Comment by royken** [comment]
As @Darkarmour  said, I downgraded to version 0.12.0
```
cordova plugin rm cordova-plugin-firebase-analytics --save
cordova plugin add cordova-plugin-firebase-analytics@0.12.0 --save
```

**Comment by Darkarmour** [comment]
It solved the above issue. But facing other issues because of the downgrade. How about for you? @royken

**Comment by Lukizzle** [comment]
Okay, I can confirm that the error disappears for the analytics plugin when downgrading to 0.12.0. However, I kept receiving the same error because of firebase messaging, so I also had to downgrade firebase messaging to 0.11.0 (mind the 11!) to make the error disappear entirely. Still, I keep running into new errors ever since and didn't manage to build the project yet - so I'm not sure if this is actually the best way.

**Comment by royken** [comment]
@Darkarmour  no more issues. Note, I don't use FCM but onesignal. 
@Lukizzle you must ensure yoursel that you use excatly the same version of goole-servive, since it depends on each plugin. Firebase analytics has its own and FCM has its own.

**Comment by Lukizzle** [comment]
Do you mean cordova-support-google-services? How do I make sure they all use the same version?

**Comment by stoconnor** [comment]
Edit your project properties and explicitly add the version.

From:
`cordova.system.library.7=com.google.firebase:firebase-dynamic-links:$FIREBASE_VERSION`
To: 
`cordova.system.library.7=com.google.firebase:firebase-dynamic-links:11.0.+`

Also best to ensure that you update your firebase core/messaging and play-services to the same version:
```
cordova.system.library.3=com.google.firebase:firebase-core:11.0.+
cordova.system.library.4=com.google.firebase:firebase-messaging:11.0.+
cordova.system.library.5=com.google.android.gms:play-services-auth:11.0.+
cordova.system.library.6=com.google.android.gms:play-services-identity:11.0.+
```

After making these changes I ran into another error:
`Cannot add task ':processArmv7DebugGoogleServices' as a task with that name already exists.`

This means there is a duplicate task to do the same thing... To fix this, simply comment out the task in the plugin file of /platforms/android/cordova-support-google-services/APPNAME-build.gradle

```
//ext.postBuildExtras = {
//    apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
//}
```

**Comment by mikamboo** [comment]
Hi @pwespi !

Wich version of fcm pluging did you add into your config.xml ?

**Comment by mikamboo** [comment]
@pwespi I use `2.1.2` for FCM plugin

```xml
<plugin name="cordova-plugin-fcm" spec="2.1.2" />
<plugin name="cordova-plugin-firebase-analytics" spec="~0.12.1">
     <variable name="FIREBASE_VERSION" value="11.0.+" />
</plugin>
<plugin name="cordova-plugin-firebase-dynamiclinks" spec="~0.10.1">
     <variable name="APP_DOMAIN" value="africa-up.io" />
     <variable name="APP_PATH" value="/" />
 </plugin>
```

**Comment by chemerisuk** [comment]
I believe the issue was because some people used old versions of cordova-cli. Version 1 includes updated <engines> section that forces to use a valid version.
